channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.6
  - snakemake =5.14
  - yaml
  - pandas
  - graphviz
  - networkx
  - pygments
  - pygraphviz
  - psutil
  - pytest
  - jinja2
