name: thumper
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - mamba
  - pandas=1.1.1
  - python>=3.7
  - snakemake=5.24.1
#   - yaml
#   - graphviz
#   - networkx
#  - pygments
#   - pygraphviz
#   - psutil
#   - pytest
#   - jinja2
