site_name: elvers
site_url: http://dib-lab.github.io/elvers/
repo_name: elvers
repo_url: https://github.com/dib-lab/elvers
edit_uri: ""

extra_css: css/custom.css

copyright: 'Copyright &copy; 2018 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis
<br/><br/>
Icon made by Freepik, obtained from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>, used under a <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> license.'

# change directory names here
docs_dir: docs
site_dir: site

theme:

  # the next 2 lines are required to use the DIB version
  name: null
  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'darkblue'
    accent: 'blue'
  
  # fun logos! see https://material.io/icons/
  logo: 'img/eel.svg'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css

# give a title for each page
nav:
  - 'elvers' : 'index.md'
  - 'About': 'about.md'
  - 'Quickstart': 'quickstart.md'
  - 'Choosing and Configuring Workflows': configure.md
  - 'Available Workflows':
    - 'Eel Pond Protocol': eel_pond_workflow.md
    - 'Protein-level Assembly Workflow': protein_assembly_workflow.md
    - 'Subworkflows':
      - 'preprocess': preprocess.md
      - 'kmer_trim': kmer_trim.md
      - 'assemble': assemble.md
      - 'annotate': annotate.md
      - 'quantify': quantify.md
      - 'diffexp': diffexp.md
      - 'sourmash_compute': sourmash_compute.md
      - 'plass_assemble': plass_assemble.md
      - 'paladin_map': paladin_map.md
      #- 'correct_reads': correct_reads:.md
    - 'Programs Used':
      - 'get_data': get_data.md
      - 'fastqc': fastqc.md
      - 'trimmomatic': trimmomatic.md
      - 'khmer': khmer.md
      - 'trinity': trinity.md
      - 'get_reference': get_reference.md
      - 'dammit': dammit.md
      - 'sourmash': sourmash.md
      - 'salmon': salmon.md
      - 'deseq2': deseq2.md
      - 'plass': plass.md
      - 'pear': pear.md
      - 'paladin': paladin.md
      - 'rcorrector': rcorrector.md
  - 'For Developers':
    - 'Under the Hood': under_the_hood.md


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
