
  ####################  Eelpond Pipeline Configfile  ####################  
basename: eelpond
experiment: _experiment1
samples: samples.tsv

  ####################  assemble  ####################  
get_data:
  download_data: false
khmer:
  C: 3
  Z: 18
  coverage: 20
  diginorm: true
  extra: ''
  ksize: 20
  memory: 4e9
trimmomatic:
  adapter_file:
    pe_name: TruSeq3-PE.fa
    pe_url: https://raw.githubusercontent.com/timflutre/trimmomatic/master/adapters/TruSeq3-PE-2.fa
    se_name: TruSeq3-SE.fa
    se_url: https://raw.githubusercontent.com/timflutre/trimmomatic/master/adapters/TruSeq3-SE.fa
  extra: ''
  trim_cmd: ILLUMINACLIP:{}:2:40:15 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:15 MINLEN:35
trinity:
  add_single_to_paired: false
  extra: ''
  input_kmer_trimmed: true
  input_trimmomatic_trimmed: false
  max_memory: 30G
  seqtype: fq

  ####################  annotate  ####################  
dammit:
  busco_group:
  - metazoa
  - eukaryota
  db_dir: databases
  db_extra: ''
sourmash:
  extra: ''

  ####################  quantify  ####################  
salmon:
  index_params:
    extra: ''
  quant_params:
    extra: ''
    libtype: A

  ####################  diffexp  ####################  
deseq2:
  contrasts:
    time0-vs-time6:
    - time0
    - time6
  gene_trans_map: true
  pca:
    labels:
    - condition
