salmon:
  elvers_params:
    outdir: quant
    inputs:
      read:
        - trimmed
        - raw
      reference:
        - transcriptome
    outputs:
      - counts
    extensions: 
      read:
        combine_units: True
        pe:
          - _x___reference__.salmon/quant.sf
          - _x___reference__.salmon/lib_format_counts.json
        se:
          - _x___reference__.salmon/quant.sf
          - _x___reference__.salmon/lib_format_counts.json
      base:
          - .salmonindex
  program_params:
    input_trimmomatic_trimmed: True
    index_params:
      extra: '' # extra info for the program
    quant_params:
      libtype: A
      extra: ''
