salmon:
  elvers_params:
    input_options:
      trimmed:
        indir: preprocess
        extensions:
          read:
            pe:
              - "_1.trim.fq.gz"
              - "_2.trim.fq.gz"
            se:
              - "_se.trim.fq.gz"
      raw:
        indir: input_data
        extensions:
          read:
            pe:
              - "_1.fq.gz"
              - "_2.fq.gz"
            se:
              - "_1.fq.gz"
    outputs:
      outdir: quant
      extensions: 
        read:
          combine_units: True
          pe:
            - _x___reference__.salmon/quant.sf
            - _x___reference__.salmon/lib_format_counts.json
          se:
            - _x___reference__.salmon/quant.sf
            - _x___reference__.salmon/lib_format_counts.json
        base:
          - .salmonindex
  program_params:
    input_trimmed: True
    index_params:
      extra: '' # extra info for the program
    quant_params:
      libtype: A
      extra: ''
