sourmash:
  elvers_params:
    input_options:
      read:
        - trimmed
        - raw
      reference:
        - fasta
    outputs:
      name: sourmash_signature
      outdir: sourmash 
      extensions: 
        base:
          - .sig
        read:
          pe:
            - .paired.khmer.fq.sig
          se:
            - .se.khmer.fq.sig 
  program_params:
    input: 
      - kmer_trimmed
      - fasta
    k_size: 31
    scaled: 1000
    extra: ''
