sourmash:
  elvers_params:
    input_options:
      trimmed:
        indir: preprocess
        extensions:
          read:
            pe:
              - "_1.trim.fq.gz"
              - "_2.trim.fq.gz"
            se:
              - "_se.trim.fq.gz"
      raw:
        indir: input_data
        extensions:
          read:
            pe:
              - "_1.fq.gz"
              - "_2.fq.gz"
            se:
              - "_1.fq.gz"
      reference:
        indir: assembly
        extensions:
          base:
            - .fasta
    outputs:
      outdir: sourmash 
      extensions: 
        base:
          - .sig
        read:
          pe:
            - .paired.khmer.fq.sig
          se:
            - .se.khmer.fq.sig 
  program_params:
    k_size: 31
    scaled: 1000
    extra: ''
