sourmash:
  elvers_params:
    outdir: sourmash 
    inputs:
      read:
        - kmer_trimmed
        - trimmed
        - raw
      reference:
        - transcriptome
        - protein
        - genome
    outputs:
      read:
        - sourmash_signature
      reference:
        - sourmash_signature
    extensions: 
      base:
        - .sig
      read:
        pe:
          - .paired.khmer.fq.sig
        se:
          - .se.khmer.fq.sig 
  program_params:
    k_size: 31
    scaled: 1000
    extra: ''
