tximport:
  elvers_params:
    input_options:
      read:
        - salmon_quant
    output_options:
      transcript_counts:
        input: salmon_quant
        outdir: quant
        combine_units: True # needs to match with salmon's combine_units
        extensions:
          base:
            - .txCounts.tsv
      gene_counts:
        input: salmon_quant
        outdir: quant
        combine_units: True # needs to match with salmon's combine_units
        extensions:
          base:
            - .geneCounts.tsv
    help: "tximport is used to aggregate counts from salmon quantification"
    citations: 
      - "Charlotte Soneson, Michael I. Love, Mark D. Robinson (2015): Differential analyses for RNA-seq: transcript-level estimates improve gene-level inferences. F1000Research http://dx.doi.org/10.12688/f1000research.7563.1"
  program_params:
    inputs: 
      - salmon_quant
    outputs:
      - gene_counts
    gene_trans_map: True
    count_type: counts # countsFromAbundance, scaledTPM, lengthScaledTPM
