trinity:
  elvers_params:
    input_options:
      read:
        - kmer_trimmed
        - trimmed
        - raw
    outputs:
      outdir: assembly
      extensions:
        reference_extensions: # use this extension only for all output of this assembler
          - _trinity
        base:
          - .fasta
          - .fasta.gene_trans_map
  program_params:
    # input kmer-trimmed reads
    input_kmer_trimmed: True
    # input trimmed-reads
    input_trimmed: False
    # do we want to assemble the single reads with pe reads?
    add_single_to_paired: False
    max_memory: 4G
    seqtype: fq
    extra: ''

