trinity:
  elvers_params:
    input_options:
      kmer_trimmed:
        indir: preprocess
        extensions:
          read:
            pe:
              - '_1.khmer.fq.gz'
              - '_2.khmer.fq.gz'
              - '.paired.khmer.fq.gz'
              - '.single.khmer.fq.gz'
            se:
              - '.se.khmer.fq.gz'  
      trimmed:
        indir: preprocess
        extensions:
          read:
            pe:
              - "_1.trim.fq.gz"
              - "_2.trim.fq.gz"
            se:
              - "_se.trim.fq.gz"
      raw:
        indir: input_data
        extensions:
          read:
            pe:
              - "_1.fq.gz"
              - "_2.fq.gz"
            se:
              - "_1.fq.gz"
    outputs:
      outdir: assembly
      extensions:
        reference_extensions: # use this extension only for all output of this assembler
          - _trinity
        base:
          - .fasta
          - .fasta.gene_trans_map
  program_params:
    # input kmer-trimmed reads
    input_kmer_trimmed: True
    # input trimmed-reads
    input_trimmed: False
    # do we want to assemble the single reads with pe reads?
    add_single_to_paired: False
    max_memory: 4G
    seqtype: fq
    extra: ''

