channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=3.5.1
  - bioconductor-deseq2=1.20.0
  - bioconductor-genomeinfodbdata
  - bioconductor-genomeinfodb
  - bioconductor-biocparallel
  - bioconductor-tximport
