dammit:  
  elvers_params:
    outdir: annotation
    inputs:
      reference:
        - transcriptome 
    outputs:
      reference:
        - transcriptome
    help: "Dammit is a de novo transcriptome annotation program. Please input a reference to annotate, or generate one via a de novo assembly program"
    extensions: 
      base: 
        - .dammit.gff3
        - .dammit.fasta
  program_params:
    db_dir: databases
    db_extra: '' 
    db_install_only: False
    annot_extra: " --quick "
    busco_group:  
      - metazoa
      - eukaryota
