dammit:  
  elvers_params:
    input_options:
      reference:
        - fasta
    outputs:
      name: dammit_annotation
      outdir: annotation
      extensions: 
        base: 
          - .dammit.gff3
          - .dammit.fasta
    help: "Dammit is a de novo transcriptome annotation program. Please input a reference to annotate, or generate one via a de novo assembly program"
  program_params:
    input:
      - fasta
    db_dir: databases
    db_extra: '' 
    db_install_only: False
    annot_extra: " --quick "
    busco_group:  
      - metazoa
      - eukaryota
