fastqc:
  elvers_params:
    citations:
      - "FastQC A Quality Control tool for High Throughput Sequence Data http://www.bioinformatics.babraham.ac.uk/projects/fastqc/ by S. Andrews"
    help: "fastqc is used to QC reads"
    input_options:
      trimmed:
        indir: preprocess
        extensions:
          read:
            pe:
              - "_1.trim.fq.gz"
              - "_2.trim.fq.gz"
            se:
              - "_se.trim.fq.gz"
      raw:
        indir: input_data
        extensions:
          read:
            pe:
              - "_1.fq.gz"
              - "_2.fq.gz"
            se:
              - "_1.fq.gz"
    outputs:
      outdir: preprocess/fastqc
      extensions: 
        read:
          pe:
            - '_1_fastqc.zip'
            - '_1_fastqc.html'
            - '_1.trim_fastqc.zip'
            - '_1.trim_fastqc.html'
            - '_2_fastqc.zip'
            - '_2_fastqc.html'
            - '_2.trim_fastqc.zip'
            - '_2.trim_fastqc.html'
          se:
            - '_1_fastqc.zip'
            - '_1_fastqc.html'
            - '_se.trim_fastqc.zip'
            - '_se.trim_fastqc.html'
  program_params:
    input_trimmed: True
    input_raw: True
    extra: ''
