rcorrector:
  elvers_params:
    input_options:
      read:
        - trimmed
        - raw
    outputs:
      name: rcorrector_trimmed
      outdir: 'preprocess/rcorrector'
      extensions:
        read:
          combine_units: False
          pe:
            - "_1.rcorr.fq.gz"
            - "_2.rcorr.fq.gz"
          se:
            - ".se.rcorr.fq.gz"
  program_params:
    input_trimmed: True
    extra: ''
