rcorrector:
  elvers_params:
    outdir: 'preprocess/rcorrector'
    inputs:
      read:
        - trimmed
        - raw
    outputs:
      read:
        - rcorrected
    extensions:
      read:
        combine_units: False
        pe:
          - "_1.rcorr.fq.gz"
          - "_2.rcorr.fq.gz"
        se:
          - ".se.rcorr.fq.gz"
  program_params:
    input_trimmed: True
    extra: ''
